services:
  registry:
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      # 如果你需要简单的账号密码验证，取消下面两行的注释
      # REGISTRY_AUTH: htpasswd
      # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - /var/lib/registry:/var/lib/registry
      # 如果配置了验证，需要挂载包含 htpasswd 文件的目录
      # - ./auth:/auth